name: 自动续期DigitalPlat Free Domains

on:
  schedule:
    - cron: '0 8 */15 * *'
  
workflow_dispatch:

jobs:
  renew:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Playwright browsers and dependencies
        run: playwright install --with-deps chromium

      - name: Run Renewal Script
        env:
          DP_EMAIL: ${{ secrets.DP_EMAIL }}
          DP_PASSWORD: ${{ secrets.DP_PASSWORD }}
          BARK_KEY: ${{ secrets.BARK_KEY }} 
          BARK_SERVER: ${{ secrets.BARK_SERVER }}
          
      - name: Upload error screenshot
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: error-screenshot
          path: error_screenshot.png
